# docker-compose.yml
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d chatbot_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=1212
      - POSTGRES_DB=chatbot_db

volumes:
  postgres_data: